micronaut:
    application:
        name: clientpooltest
    server:
        port: 8080
        idleTimeout: PT15S
    http:
        client:
            read-timeout: PT2S
            read-idle-timeout: PT5S
            pool:
                enabled: true
                max-connections: 10
                max-pending-acquires: 1
                acquire-timeout: PT0S
